### ISSUE TITLE
Tab scrolling and indicator positioning is incorrect when there are many tabs and `isScrollable=true`

### ISSUE THREAD

**Issue by ywake** [OrtakProje-1/reorderable_tabbar#1]
Thanks for developing this plugin. This has saved my time.

I found one problem.
When there are too many tabs  and their length exceeds some threshold, the scrolling and indicator positions become incorrect.

https://user-images.githubusercontent.com/59673834/179913523-3a641c13-2152-48ed-b0b5-1d2abb82bd49.mov

**Comment by ywake** [comment]
I think this is the cause.
https://github.com/OrtakProje-1/reorderable_tabbar/blob/a63b5805f731982dd4cdfb6a15ad33b167c89739/lib/reorderable_tabbar.dart#L810
The `key.currentContext` is often null, in which case the width is set at 40, causing the misalignment.

**Comment by OrtakProje-1** [comment]
thanks mate i will check it out
